### ISSUE TITLE
Integrate python module in Gym

### ISSUE THREAD

**Issue by edran** [facebook/MazeBase#11]
Now that we have a python version available, we should integrate it with OpenAI Gym.

## TODO

- [ ] Standardise a bunch of environments
  - [ ] text based envs
  - [ ] image based envs ?
- [ ] Create gym-wrapper (likely as another repo)

@ebetica and I will look at this in a couple of weeks, but if anyone else wants to do it, please go ahead!

**Comment by zuoxingdong** [comment]
@edran I am doing a master project related to Grid world. So I would like to contribute a bit. During next few weeks I shall go through source code firstly and then to work on a Gym wrapper.

**Comment by edran** [comment]
Hi @zuoxingdong, what we probably currently need help with right now is testing the library and sorting #12 out. We are going to think a bit more about the gym wrapper, so that we can come up with a good set of tasks to package.
